export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const GET_REPS = 'GET_REPS'
export const GET_USER = 'GET_USER'
export const SEARCH_USERS = 'SEARCH_USERS'
export const SET_LOADING = 'SET_LOADING'